services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arise
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    container_name: api
    build: 
      dockerfile: docker/Dockerfile.server
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@database:5432/arise

volumes:
  postgres_data: